#setup port cua app
server:
  port: 8080
  servlet:
    context-path: /identity
#    dinh vi duoc microservice


#ket noi database jpa vs mysql
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identity-service"
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    user:
      name: admin
      password: 123456
jwt:
  signerKey: "v0yKrFkJyREX/RXFr4vr8exjiOawBMySpWNWKBQBZcIqNzpTR9GuMRss4CKNe4Cd"

